site_name: RetailPulse Docs
theme:
  name: material
  features:
    - navigation.expand
nav:
  - Home: index.md
  - Functional Docs: functional_docs.md
  - Technical Docs:
      - Tech Stack: technical/tech_stack.md
      - Data Flow: technical/data_flow.md
      - Authentication: technical/auth.md
      - Schema Design: technical/schema_design.md
      - Architecture: technical/architecture.md
      - CI/CD: technical/ci_cd.md
      - API Design: technical/api_design.md
      - Testing: technical/testing.md
  - Use Cases: use_cases.md
  - Edge Cases & Error Handling: edge_cases.md
  - Future Enhancements: future_enhancements.md
  - Development Workflow & Testing: development_workflow.md
  - SAST/DAST: sast_dast.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - to-pdf:
      output_path: pdf/document.pdf
